### ISSUE TITLE
design of labels and for_each

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#14]
The regular for loop is allowed in step action but it is difficult to run them in parallel because step action can be very complicated. The `for_each` parameter is designed to repeat the action with different values in parallel.

That is to say

```python
input: for_each='method'

run('command1 ${_method}')
```

is more or less equivalent to 

```python
for _method in method:
    run('command1 {}'.format(_method))
```

String interpolation cannot be used because SoS does not understand the loop.

I am not sure the current design is intuitive though. It requires the variables to be defined before and uses a derived variable (`_name` for variable `name`), but the usual `for_each` loop does not fit into the existing parameter structure.

Another concern is that we are using `input` for both regular and looped cases. It might
make sense to use `_input` for the latter.

**Comment by gaow** [comment]
I find the current design intuitive. For looped case the looped parameter is prefixed by `_` and apparently SoS interpreter is currently smart enough to tell that and properly decide the behavior of `input`

**Comment by bpeng2000** [comment]
Ok, I am glad that you find it intuitive, perhaps we need better naming for
the parameter and better documentation. Please help update the doc.

for_each is ok, candidates for labels include

1. label
2. matched, attach
3. tag, file_tag
4. attribute, mark
5. alias, file_alias
6. zip, tied_to
7. clip, clipper, sticker

I think this is a useful feature because it is easier to use than setting
up dictionaries for properties of filenames but finding a good name is not
easy.

Bo

**Comment by gaow** [comment]
Yes it is quite easy to edit doc on the browser now; I update it as I find it not clear. The name is hard ...

8. paired_with
9. associated
10. bind, bind_with (bind_to?)
 
My contention against label or tag was that label or tag sounds like something for annotation purpose of the same object, and there is usually only one label or tag -- neither is true for our case.

**Comment by gaow** [comment]
I'm thinking of this scenario:

```python
p1 = [1, 2]
p2 = [3, 4]
res = [a.txt, b.txt, c.txt, d.txt]
input: for_each = ['p1', 'p2'], paired_with = 'res'
run('exe -p1 ${_p1} -p2 ${_p2} -o ${_res}')
```
so that the resulting commands can be:
```
exe -p1 1 -p2 3 -o a.txt
exe -p1 1 -p2 4 -o b.txt
exe -p1 2 -p2 3 -o c.txt
exe -p1 2 -p2 3 -o d.txt
```

Under the current framework the only way to achieve this is to create another variable that combines `p1` and `p2` and then `paired_with` (`label` for now) `res`. I'm wondering if something like above will be good to have, i.e., first apply `for_each`, then `paired_with`?

**Comment by bpeng2000** [comment]
The problem is that there can be uncertainties with order of execution especially when group_by and for_each are both used. In the current implementation, step process knows `_input`, `_label`, and `_loop` and can determine the output from such information. Users can even use

```python
output: '%{_label}_${loop}.out'
```

to specify output and do not have to worry about exactly how many output files will be generated and in which order. If such usage is important to you, we can expose an `_idx` (or `_group`) variable so that you can do

```
p1 = [1, 2]
p2 = [3, 4]
res = [a.txt, b.txt, c.txt, d.txt]
input: for_each = ['p1', 'p2']
run('exe -p1 ${_p1} -p2 ${_p2} -o ${res[_idx]}')

**Comment by gaow** [comment]
I think it would be a common user case in simulation or statistical analysis (e.g. runs with different tuning parameters). The label / loop is one way out but it will be difficult to match output name with proper parameter input ...

If the syntax I proposed will cause trouble, an alternative is to store all these parameters in data base separately (like I proposed for the `runtime.db`) so that users can query the output name by parameter.  This is somewhat troublesome but at least makes it tractable. Otherwise it will not be possible to locate the correct output for the best tuning parameters for example.

**Comment by gaow** [comment]
And sorry I did not get your proposed `_idx` syntax ...

**Comment by gaow** [comment]
For my application for now please do not worry. I will create proper names from the input, i.e., expand the `p1` and `p2` list so that they match the list of `res`, then use existing syntax. This might also be our answer to this -- we allow for flexibility with advanced usage although users have to do a little more work.

**Comment by bpeng2000** [comment]
My proposal aims exactly to match output name with parameter input, namely
coding parameters in output file names ('${_label}{_loop}`. Otherwise it is
too difficult to figure out which output correponds to which input.

Bo

**Comment by bpeng2000** [comment]
I just tested a case like that

```python
[0]
files = ['a.txt', 'b.txt']
par = [(1, 2), (1, 3), (2, 3)]
res = ['p1.txt', 'p2.txt', 'p3.txt']
processed = []

input: files, for_each='par,res'
output: res

processed.append((_par, _res))
```

`processed` is ` [((1, 2), 'p1.txt'), ((1, 3), 'p2.txt'), ((2, 3), 'p3.txt')])` after execution.

**Comment by bpeng2000** [comment]
`labels` renamed to `paired_with`.
