### ISSUE TITLE
Getting ride of looping features of input?

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#38]
The differences between `_step.input`, `_input`, `_output`, `_step.output` , `loop_var` and `_loop_var` can be confusing. I am wondering if there can be ways to completely remove loops from steps. For example, we can move the loop to the section option level (but that place is crowded as well). 

To the very least we need a good figures to explain these variables well.

**Comment by gaow** [comment]
I'm not sure if I get the problem: loop_var means `for_each` option and that's to be removed? I doubt that's what you mean because that will also involve `pattern`. I'm wondering:

1. Can we make sure that `_` is exclusively for loop var, and without `_` it always means that variable it self? My understanding is that `_n` is like `n[i]` and, for variables in `pattern` the same should hold, i.e., 
`pattern = '{base}.{ext}'` then `${_base}` means looping through all `base[0], ... base[N]` and `${base}` means consolidating them all together. Same for `_input` vs `input`, `_output` vs `output`.

2. This will leave `_step` the only exception, in which case we replace it by another keyword like `self`? 

I know this will be big changes but just throwing some thoughts here. The loop seems a frequently used feature too crowded to be in section option level.

**Comment by bpeng2000** [comment]
_ means local so _step is in line with _input and _output. The input loop
feature introduces so many new vars and I think we need to explain better.
Perhaps we can intruduce all non loop features and put all looping features
in a separate section.

**Comment by gaow** [comment]
Yes I understand that `_` currently has two uses: local and loop var -- is loop var prefixed by `_` because it is local or because it is loop var? I believe this is where the confusion is. I was saying that perhaps change the notation to let `_` dedicate to loop var, because there are potentially so many of them, and find something else for local variables?

**Comment by gaow** [comment]
Or the other way around -- another syntax for loop var.

**Comment by bpeng2000** [comment]
The complexity seems to be unavoidable. Let us see if better documentation can make things easier to understand.
