### ISSUE TITLE
Addition of step process keyword

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#43]
Our step current has format 

```
input:
output:
depends:
runtime:
```

with assignment allowed before/between these keyword, and any statement after the last keyword is considered as step process. This is clear enough in most cases but it might be clearer to have a separate `process` keyword that begins the step process. For example, a problem an advanced user might encounter is that

```
input:
_output = some_user_function()
```
will not work because `_output` is part of the step process so change of `_output` will not affect step output (unless he adds another keyword after the statement). It would be clearer to write this particular example as

```
input:
_output = some_user_function()

process:
start of process
```

**Comment by bpeng2000** [comment]
Another consideration is that we can consider everything after `process` as real processes that will be executed in separate process, and steps with `process` as inline process that will be executed with SoS. This might be acceptable given that many jobs will be small and do not need to be executed in separate processes.

**Comment by gaow** [comment]
Is this to say that everything after `process` are local to a process, and otherwise are in the SoS global name space? I am trying to think of a scenario where after `process` is done you want to modify global SoS variables based on some outcome from `process`. I cannot have a concrete example but that scenario does seem possible, if my understanding of the problem is correct .

**Comment by bpeng2000** [comment]
Yes. Right now we only know if the subprocess has been executed successfully.

**Comment by bpeng2000** [comment]
Close the ticket now because the remaining issue is discussed in the 'shared' option thread.
