### ISSUE TITLE
Disallow the change of SoS environment in step process.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#46]
Right now at least in test scripts, step processes are executed in SoS local namespace and can, for example run

```
executed = []

[10]
executed.append(_step.name)
```

This is ok for now but will significantly complicate the implementation of parallel execution of scripts because step processes would then all reply on the same central global environment, causing a lot of inter-process troubles. It would make sense to **copy** runtime variables to step processes and let the process execute independently. That is to say, change of local namespace will not affect SoS. 

Changes that have been made:

1. A `process` keyword is used to replace `runtime`, basically runtime option is now process runtime options.

2. All statements are now allowed in a SoS step and are executed in SoS namespace.

3. Step processes are executed in a separate process that is independent of SoS.

That is to say, the above example will continue to work because everything is still in SoS namespace.

**Comment by gaow** [comment]
But if I have a scenario where there is a gobal variable defined as, say "previous_step_success = True" then have every step check if it is `True` in order to proceed, and write it to `False` if current step fails so the next step will see it -- this is just a dumb example of a case where the variable changed in previous step matters to the next. Will the current implementation allows for things like this if things go parallel? Or i assume one has to manually specify dependencies between previous and current steps in order for this to work?

**Comment by bpeng2000** [comment]
The rule now is that everything after 

```
process:
statements
```

or its script format version

```
action:
script
```
 
are executed in their own processes. Change of variables does not affect the SoS process and we explicitly require all subprocesses to return 0 to assert successful execution. Your problem can be solved (sort of) by using inline action (use `run()` etc without `process:`) but I agree this should be better solution.

Perhaps we can design a runtime option somehow.

**Comment by bpeng2000** [comment]
The behavior is again changed for consistency. That is to say, step process is not automatically executed in a separate process, so 

```
run:
    command
```

is merely a shortcut for

```
process:
run(`command`)
```

Only when the `concurrent=True` is set in form of

```
process: concurrent=True
run(`command`)
```

or

```
run: concurrent=True
  command
```

will the step process be executed in separate process(es).

The less magic rules, the better.
