### ISSUE TITLE
__future__ like feature to disable special SoS syntax.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#50]
The use of special syntax in SoS might be troublesome. For users who would prefer authentic Python interpreter, we might be able to provide something like

```
from pysos import no_raw_tripple_string, no_string_interpolation
```

and disable these SoS added features.

**Comment by gaow** [comment]
I'm not sure if it is necessary to have this alternative option. SoS has its own syntax, which is based on Python but with variations. Users should learn and use SoS syntax though knowledge of Python will help greatly. We should fix SoS syntax if it causes real trouble (more than troublesome); otherwise learning some extra SoS special is fair enough. 

Also, is it possible now to import packages like this in a SoS script? I recall it is not possible at least last week.

**Comment by bpeng2000** [comment]
Yes, import is allowed. Although string interpolation is fairly useful, I am now not entirely sure about treating `''' '''` as raw string. The motivation was that we would use a lot of triple quotes and having to use the `r` prefix is kind of awkward. However, with the introduction of script format of step process, we should see a dramatic decrease of triple quotes so changing default python behavior might not worth the trouble.
