### ISSUE TITLE
SoS "derived" steps / steps repository

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#70]
Now that we have docker support we are comfortable in not having reproduciblity issues due to software / resources used. I think it should really be helpful to create an online repository for SoS steps. snakemake currently has [some but not many workflows](https://bitbucket.org/johanneskoester/snakemake-workflows/src/fa47806ee1dabda8f1ac77877bc831d1f2c8b9f9?at=master). We should not directly run `ngseasy` scripts either because the workflow control is not as good there. (e.g., `while` loop in shell is used to run multiple commands!!). I'm wondering we should have a way to "derive" one step from others, and hopefully save many commonly used "base" steps to a repository. For example

```
[mapping_1: alias = 'bwa']
input: ...
output: ...
run: ...

[mapping_2: base = 'bwa', alias = 'bowtie']
run: ...
```

Where `mapping_2` is derived from `mapping_1` so that same input files are used but possibly a different command is executed (this may not be a good example ... I'm just trying to see if there seems to be a need to derive a step from the same file). Or, 

```
[mapping_1: base = 'http://URL/bwa.sos', alias = 'bwa']
input: ...
output: ...
```

Where we load a step from a repository and overwrite its input/output so that we do not have to write the actual command. Modularizing SoS steps and make them into repos will further help reproducibility. 

A downside is that SoS will be less self-contained. This is always the cost of being modular I assume.

**Comment by bpeng2000** [comment]
Are you sure you want to go into the service provider without pay business? ngsease got a grant so they have the man/money power to provide and maintain pipelines. snakemake does not have many pipelines because people are not willing to share/maintain pipelines. There were a few users who used VPT and asked questions but no one contributed to VPT. 

The problem was mostly with maintainability because tools change fast so workflows require constant upgrade, and the workflows were not applicable most of the times due to compatibility issues. Dockerization certainly solves some problems but not all, as you can see from the ngsease guys who are 'refacterizing' ngsease due to most likely inflexibility of their workflows. I had a look at their pipelines and I would say using SoS to rewrite those shell scripts would be a great time-saver.

That said (vented), I agree that we can make things a bit easier. However, I do not see a clear case of yours because nested workflow seems to work just all right there. In terms of flexiblity (using alternative step etc), https://github.com/bpeng2000/SOS/issues/69 might be more urgent and I do like the syntax of the last example.

**Comment by gaow** [comment]
Yes I read into #69 after I posted. It is also related to modularization and is good design. I agree we should not provide any services. I was thinking of the need and possible ways we store and reuse use some shared steps in multiple SoS scripts, to make our work easier. It might be useful when you have multiple NGS variant calling projects each with a script that uses some common shared steps. The downside is that we will need version control for these shared script so that updates will not break existing scripts ( maybe having them on git make this easier).

**Comment by bpeng2000** [comment]
Close for now. Please provide a concrete application case with perhaps an example and proposed syntax in a new ticket.
