### ISSUE TITLE
A wrapper action for subprocess.check_output

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#89]
I'm wondering if we should add an action to make a short-cut for this:

`subprocess.check_output('ls | head', shell=True).strip().decode('utf8').split('\n')`

because it seems a very frequently used action.

**Comment by bpeng2000** [comment]
Name?

**Comment by gaow** [comment]
`get_output`? I know it is most difficult to come up with a name for it. I'm out of ideas ... This is a potentially dangerous so I guess the same safety mechanism for `check_command` will be used here.

**Comment by bpeng2000** [comment]
Behavior of not completing in 5 seconds, warning or error? 
Behavior of returning non-zero, warning or error?

I suppose both can raise error.

**Comment by gaow** [comment]
I'm not sure ... because unlike `check_command`, sometimes a line count `wc -l` can take rather long time, though. Perhaps warning? It is then user's responsibility to deal with it.

**Comment by bpeng2000** [comment]
You know all statements would be killed after 5 seconds in dryrun mode, right? Only actions in run mode can last longer.

**Comment by gaow** [comment]
Right. I think it is fair enough. We force some unhappiness here to encourages users to cache the results (via a dedicated step) for long lasting command like wc or grep on large files.

**Comment by bpeng2000** [comment]
I am not sure we should define an action just for this if there is no added value for being an action (it always runs), and it does not seem to worth the trouble of defining a function that has to be imported from sos...

**Comment by gaow** [comment]
The only other function from sos is `expand_pattern()`, right? Was that automatically imported to SoS domain? Maybe instead of action we just define a `get_output` function like `expand_pattern()`. It is a bit risky but we do not claim it an action and the risk is not ours. I feel it would be annoying to realize that there is no shortcut for this, particularly for people from shell scripting background who rely on stdout a lot.

**Comment by bpeng2000** [comment]
There are two utility functions and they are by default not imported. I do not import them by default because I am afraid of name conflict, `python`, `run`, `get_output` are quite common names and I am afraid more such functions can cause mysterious error. This is another issue but I suppose we can

1. Get a list of sos symbols and disallow re-definition of them in SoS script. That is to say, we disallow things such as `def run` and `run = 5`.

2. Use aliases. For example, we prefix all actions with `action` and import names such as `action_run`, and we translate all actions to `action_func`. This is doable because SoS can recognize actions by their decoration.

**Comment by gaow** [comment]
It sounds like 2 is most straightfoward. If you are not happy calling `get_output` or something else an action I suppose we can decorate with another symbol and handle that.

**Comment by bpeng2000** [comment]
Implementation wise both are not very difficult because we evaluate everything in our dictionary. Option 2 has the disadvantage that users have to remember another rule. This is not an urgent issue though.

Are you ok with 'from pysos import get_output'?

I also would like to have `get_output` to return the complete output because I think most of the time users would like to use the complete output or first line and you are forcing users to use `get_output(cmd)[0]` a lot. We should also add option `stderr=True/False` to also return `stderr`. I suppose there is no value of only get `stderr` ( `get_output(stdout=False, stderr=True)`)?

**Comment by bpeng2000** [comment]
I actually noticed that `expand_pattern` etc are available directly.

**Comment by gaow** [comment]
> I actually noticed that expand_pattern etc are available directly.

Yes that's what I've been using. For standard output / error I'm cool with the basic feature. Users can directly interact with subprocess.check_output if they want any fancier features than this.

**Comment by bpeng2000** [comment]
OK, a basic function is implemented (without any option) and we will see if there is a need for `stderr=True`. I also updated the documentation.

**Comment by gaow** [comment]
should we add `rstrip()` after `decode()`? Or `strip()`? Currently I'll have to `get_output(xxx).rstrip().split('\n')`. This is Ok. I can live with it.
